# This is a basic workflow to help you get started with Actions

name: (ステージ環境) バックエンドのデプロイ

# Controls when the action will run.
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Public IPの取得
        id: ip
        uses: haythem/public-ip@v1.2

      - uses: actions/checkout@v2

      - name: AWS CLIをインストール
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      - name: AWS CLIのセットアップ
        run: |
          printf "${DEV_AWS_ACCESS_KEY_ID}\n${DEV_AAWS_SECRET_ACCESS_KEY}\nap-northeast-1\njson\n" | aws configure --profile monoinv-dev
          aws configure get aws_access_key_id --profile monoinv-dev
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          DEV_AAWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AAWS_SECRET_ACCESS_KEY }}

      - name: SSHポートの開放
        run: |
          # https://github.com/haythem/public-ip
          IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`
          aws --profile monoinv-dev ec2 authorize-security-group-ingress --group-id ${DEV_AWS_SECURITY_GROUP} --protocol tcp --port ${SSH_PORT_22} --cidr "$IP_ADDRESS"/32
        env:
          DEV_AAWS_ACCESS_KEY_ID: ${{ secrets.DEV_AAWS_ACCESS_KEY_ID }}
          DEV_AAWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AAWS_SECRET_ACCESS_KEY }}
          SSH_PORT_22: ${{ secrets.SSH_PORT_22 }}
          DEV_AWS_SECURITY_GROUP: ${{ secrets.DEV_AWS_SECURITY_GROUP }}
  # This workflow contains a single job called "build"
  deploy01:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 多段SSH接続 + DB マイグレーション + バックエンドデプロイ
        run: |
          echo ${CHECKOUT_REF}
          echo "deploy01"
  deploy02:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: deploy01
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 多段SSH接続 + DB マイグレーション + バックエンドデプロイ
        run: |
          echo ${CHECKOUT_REF}
          echo "deploy01"
  close_port:
    runs-on: ubuntu-latest
    needs: [deploy01, deploy02]
    steps:
      - name: SSHポートの閉鎖
        run: |
          echo ${CHECKOUT_REF}
          echo "close_port"
